# Publish joint_states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

rosbot_arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
  constraints:
    goal_time: 10.0                     # Override default
    stopped_velocity_tolerance: 0.05    # Override default
    joint_1: {trajectory: 0.1, goal: 0.05}   # Override default
    joint_2: {trajectory: 0.1, goal: 0.05}   # Override default
    joint_3: {trajectory: 0.1, goal: 0.05}   # Override default 
    joint_4: {trajectory: 0.1, goal: 0.05}   # Override default 
    joint_5: {trajectory: 0.1, goal: 0.05}   # Override default

  stop_trajectory_duration: 0.5         
  state_publish_rate:  50             # Override default
  action_monitor_rate: 30             # Override default
  allow_partial_joints_goal: true     # Override default
